name: tr_task
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  logger: ^1.1.0
  dio: ^4.0.6
  lottie: ^1.3.0
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^1.0.3
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


